version: '3'

services:
  app:
    requires:
      - redis
    build: .
    container_name: news-labels-api
    restart: always
    ports:
      - "8000:8000"
  redis:
    image: redis
    container_name: redis-news-labels-api
    command: redis-server --bind redis-news-labels-api --maxmemory 256mb --maxmemory-policy volatile-ttl --appendonly yes
    restart: always
    expose:
      - "6379"
