version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
  redis:
    image: redis
    container_name: redis-news-labels
    restart: always
    expose:
      - "6379"
